# This compose file will set up a single node kafka cluster on local along with Kafdrop UI
version: '2'
services:
  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
      - /Users/aryak/Desktop/prometheus:/etc/prometheus


  grafana:
    image: grafana/grafana-enterprise
    depends_on:
      - prometheus
    ports:
      - '3000:3000'

volumes:
  aryak-volume:
